#!/usr/bin/env bash
# generate-catalog.sh — regenerate SKILLS.md from skill frontmatter, so the
# catalog never drifts from the actual skills. Run: bash scripts/generate-catalog.sh

set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
OUT="SKILLS.md"

field() {
  awk -v f="$2" '
    NR>1 && $0=="---" { exit }
    NR>1 { if ($0 ~ "^"f":") { sub("^"f":[[:space:]]*",""); print; exit } }
  ' "$1"
}

emit_skill_row() {
  local dir="$1"
  local name file desc group
  name="$(basename "$dir")"
  file="${dir}SKILL.md"
  [ -f "$file" ] || return 0
  desc="$(field "$file" description)"
  group="$(basename "$(dirname "$dir")")"
  if [ "$group" = "marketing" ]; then
    echo "| \`$name\` | $desc |"
  else
    echo "| \`$name\` | $desc |"
  fi
}

{
  echo "# Skills Catalog"
  echo
  echo "_Auto-generated by \`scripts/generate-catalog.sh\` — do not edit by hand._"
  echo
  echo "## Engineering (SDLC)"
  echo
  echo "| Skill | Description |"
  echo "|-------|-------------|"
  for dir in skills/*/; do
    name="$(basename "$dir")"
    [ "$name" = "marketing" ] && continue
    link_path="${dir%/}"
    if [ -L "$link_path" ]; then
      target="$(readlink "$link_path" 2>/dev/null || true)"
      case "$target" in marketing/*) continue ;; esac
    fi
    emit_skill_row "$dir"
  done | sort
  echo
  echo "## Marketing (skills/marketing/)"
  echo
  echo "| Skill | Description |"
  echo "|-------|-------------|"
  for dir in skills/marketing/*/; do
    [ -d "$dir" ] || continue
    emit_skill_row "$dir"
  done | sort
  echo
  eng_count="$(find skills -mindepth 1 -maxdepth 1 -type d ! -name marketing | wc -l | tr -d ' ')"
  mkt_count="$(find skills/marketing -mindepth 1 -maxdepth 1 -type d 2>/dev/null | wc -l | tr -d ' ')"
  total=$((eng_count + mkt_count))
  echo "_$total skills ($eng_count engineering + $mkt_count marketing)._"
} > "$OUT"

echo "Wrote $OUT"
