#!/usr/bin/env bash
# generate-catalog.sh — regenerate SKILLS.md from skill frontmatter, so the
# catalog never drifts from the actual skills. Run: bash scripts/generate-catalog.sh

set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
OUT="SKILLS.md"

field() {
  awk -v f="$2" '
    NR>1 && $0=="---" { exit }
    NR>1 { if ($0 ~ "^"f":") { sub("^"f":[[:space:]]*",""); print; exit } }
  ' "$1"
}

{
  echo "# Skills Catalog"
  echo
  echo "_Auto-generated by \`scripts/generate-catalog.sh\` — do not edit by hand._"
  echo
  echo "| Skill | Description |"
  echo "|-------|-------------|"
  for dir in skills/*/; do
    name="$(basename "$dir")"
    file="${dir}SKILL.md"
    [ -f "$file" ] || continue
    desc="$(field "$file" description)"
    echo "| \`$name\` | $desc |"
  done | sort
  echo
  echo "_$(find skills -maxdepth 1 -mindepth 1 -type d | wc -l | tr -d ' ') skills._"
} > "$OUT"

echo "Wrote $OUT"
